### ISSUE TITLE
Support kwargs for loader.*_xpath()

### ISSUE THREAD

**Issue by alexander-matsievsky** [scrapy/itemloaders#32]
Allow passing named variables and `namespaces` dict arguments on `ItemLoader.*_xpath()` family of methods ([add_xpath](https://doc.scrapy.org/en/latest/topics/loaders.html#scrapy.loader.ItemLoader.add_xpath), etc.).
 
Related scrapy/scrapy#2457.

**Comment by wRAR** [comment]
I think this was done in #48?

**Comment by VMRuiz** [comment]
@wRAR  I would say yes. 

However,  I think is not added for `*_css()` methods. Does it make sense to implement it there too?

**Comment by Gallaecio** [comment]
Hmm… Does CSS syntax support variables, though? This may be XPath-specific.

**Comment by Gallaecio** [comment]
If so, we may want to consider removing `**kw` from the `_get_cssvalues signature`, so I think it makes sense to kepe this open.

**Comment by VMRuiz** [comment]
There is no references to CSS variables in Parsel lib, so I guess there is no user case for this.

**Comment by VMRuiz** [comment]
> If not, we may want to consider removing `**kw` from the `_get_cssvalues` signature, so I think it makes sense to keep this open either way.

Let's create a new issue for that to avoid having issues open forever  :smile:
