### ISSUE TITLE
Assertion error after nested

### ISSUE THREAD

**Issue by tonal** [scrapy/itemloaders#87]
If xpath in nested_xpath not exists
Code
```python
      info = loader.nested_xpath('.//div[@class="product-card__more-info"]')
      info.add_xpath('artikul', 'p[1][span/text() = "Код товара:"]/text()')
```
Assertion in **_get_xpathvalues**:
```
assert self.selector
```

**Comment by wRAR** [comment]
Can you please provide a minimal reproducible example?

**Comment by VMRuiz** [comment]
I was able to reproduce it with:
```python
from parsel import Selector
from itemloaders import ItemLoader
loader = ItemLoader(selector=Selector('<body></body>'))
nl1 = loader.nested_xpath('//missing-tag')
nl1.add_xpath('foo', './/p/text()')
```

**Comment by VMRuiz** [comment]
I'm not sure what's the expected behavior in this case:

1. Raise an error on `nested_xpath`
2. `nested_xpath` returns None
3. `nested_xpath` returns itself

I would go with `2` and let the developer check for empty values on their side.

**Comment by wRAR** [comment]
Asserts are just incorrect, `self.selector` in this case is an empty SelectorList.

**Comment by wRAR** [comment]
So _check_selector_method() checks `if self.selector is None` and asserts that are after it should do the same (those asserts are only needed for typing as mypy can't understand that _check_selector_method() did the same check)
